apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - app.yaml
  - prometheus.yaml
  - grafana.yaml
  - hpa.yaml
  - pgbouncer.yaml